project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
website:
  title: "Ciencia de datos <br>políticos con R"
  sidebar:
    collapse-level: 1
    contents:
      - text: Introducción al curso
        href: index.qmd
      - section: Ciencia de datos políticos
        contents:
            - text: Ciencias de datos y política
              href: ciencia_datos.qmd
            - text: Introducción al R
              href: S_1_IntroR.qmd
      - section: Manipulación y análisis
        contents:
            - text: Picando datos
              href: S_2_Datos.qmd
            - text: Análisis básicos
              href: S_3_Analisis.qmd
#            - text: Encuentas
#              href: encuestas.qmd
      - section: Visualización
        contents:
            - text: Fundamentos
              href: basico.qmd
            - text: Recursos útiles
              href: recursos.qmd
            - text: Gramática de los gráficos
              href: gramatica.qmd
            - text: Tipos de gráfico
              href: tipos.qmd
            - text: Apariencia y temas
              href: personalizacion.qmd
            - text: Interactividad
              href: interactivo.qmd
      - section: Textos e IA
        contents:
            - text: Análisis básico de textos
              href: AT01_explora_inductivo.qmd
            - text: Codificación y escalonado
              href: AT02_codifica_escalonado.qmd
            - text: Modelos generativos (IA)
              href: IA.qmd


  page-footer:
    left: "&copy; Copyright 2025, Rodrigo Rodrigues-Silveira"
    
execute:
  warning: false
  message: false
  error: false

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    code-fold: show
    code-overflow: wrap
  
bibliography: references.bib

editor: source

